/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_cc_jni_service_JniService */

#ifndef _Included_com_cc_jni_service_JniService
#define _Included_com_cc_jni_service_JniService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cc_jni_service_JniService
 * Method:    println
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_cc_jni_service_JniService_println
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_cc_jni_service_JniService
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cc_jni_service_JniService_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
